### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by neomooney** [4B4DB4B3/B4DB4B3-RAT#11]
Hi,
I build this project with Visual Studio Community 2019 but got these error:

...\B4DB4B3-RAT-main\B4B3-RAT\Builder\common.h(34,10): fatal error C1083: Cannot open include file: 'modes.h': No such file or directory

...\B4DB4B3-RAT-main\B4B3-RAT\Builder\common.h(34,10): fatal error C1083: Cannot open include file: 'modes.h': No such file or directory

And I use your buider but the rat cannot add to startup. Maybe you could help.
Thank you,

**Comment by 4B4DB4B3** [comment]
You need to build CryptoPP library
