### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by kup1w** [4B4DB4B3/B4DB4B3-RAT#5]
Я все делаю по инструкции все правильно все ок. Но когда заполняю все поля или даже частично то он просто создает такой же builder. То есть builder создает builder только с другим названием.  Мне кажется что он что то в коде напортачил и из-за этого он создает не приложение для получения удаленного доступа к компьютеру а builder.

**Comment by Vampire1991** [comment]
мне кажется,что ты долбаеб <3

**Comment by Vampire1991** [comment]
иди высри под сурсярами зевса,что он не работает

**Comment by kup1w** [comment]
> мне кажется,что ты долбаеб <3

а мне кажется ты еблан тупой далбаебище тупорылое иди нахуй ахуел да блять я нахуй сказал что у меня не робит билдер а ты еблан тупой ущерб без мамки высрал что какую то хуйню про зевс

**Comment by kup1w** [comment]
блять я попросил нахуй чтобы посмотрели может как то можно исправить а ты нахуй ущерб блять тупой безмамный говоришь что то про далабеба еблан тупорылый

**Comment by 4B4DB4B3** [comment]
Здравстуйте. Предоставьте GIF работы программы, либо скриншоты ввода полей. Тестировалось на виртуальных машинах и на реальных - нет никаких проблем.

**Comment by 4B4DB4B3** [comment]
Подозреваю, что у вас напутаны названия Builder'a и Stub'а. Важно, что бы названия файлов после распаковки оставались такими, как были и до распаковки.

**Comment by kup1w** [comment]
> Подозреваю, что у вас напутаны названия Builder'a и Stub'а. Важно, что бы названия файлов после распаковки оставались такими, как были и до распаковки.

Они остались такими же какими и были, я их не трогал как распаковал так сразу открыл билдер. Скриншоты в данный момент предоставить не могу.

**Comment by 4B4DB4B3** [comment]
Без доказательств работы issue не открывать, иначе заблокирую.
