### ISSUE TITLE
Update❤❤❤❤

### ISSUE THREAD

**Issue by alix1011** [4B4DB4B3/B4DB4B3-RAT#9]
Oh bro tnx tnx tnx for uppppdate❤❤😂✅

**Comment by alix1011** [comment]
My friend, do you have a telegram or a discord?

**Comment by alix1011** [comment]
@4B4DB4B3

**Comment by alix1011** [comment]
My friend, there is a bug in the rat update, it sends system information to Telegram as spam, each system must be sent once, but it is sent a thousand times in a minute.

**Comment by 4B4DB4B3** [comment]
Please, stop flood in issues.
No, I don't have a Discord or a Telegram.
You can contact me via TOX client-EC8C829C64E432B9E360E608353F28F22288876EF6129F55EBC17E3A465DF771B68DDFE2A1F1
